services:
  mongodb:
    image: mongo
    container_name: database
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - quotes-invoices-network
    environment:
      - MONGO_INITDB_DATABASE=quotes-invoices

  backend-bignova:
    # image: backend-bignova:latest
    image: ghcr.io/${GITHUB_REPOSITORY:-touahriasami/bignova-backend}:latest
    ports:
      - '4000:3000'
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_DB_URI=mongodb://mongodb:27017/quotes-invoices
      - JWT_SECRET=lksqmjfsqjfmslkdjfmlkqsjdfmlsjqfl
      - JWT_EXPIRATION=86400
    networks:
      - quotes-invoices-network
    depends_on:
      - mongodb

volumes:
  data:

networks:
  quotes-invoices-network:
    driver: bridge
